export default {
  centerBoth: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleText: {
    fontFamily: 'System',
    fontWeight: '100',
    color: 'rgba(255,255,255,1)',
    fontSize: 48,
  },
  locationText: {
    fontFamily: 'System',
    fontWeight: '100',
    color: 'rgba(255,255,255,1)',
    fontSize: 40,
  },
  buttonText: {
    fontFamily: 'System',
    fontWeight: 'normal',
    color: 'rgba(255,255,255,0.75)',
    fontSize: 30,
  },
  paragraphText: {
    fontFamily: 'HiraginoSans-W3',
    fontWeight: 'normal',
    color: 'rgba(255,255,255,0.75)',
    fontSize: 21,
    lineHeight: 24,
    textAlign: 'justify',
    width: 525,
  },
  navText: {
    fontFamily: 'System',
    fontWeight: '300',
    fontSize: 22,
    color: 'rgb(255,255,255)',
  },
  button: {
    flexGrow: 0,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.75)',
    paddingLeft: 50,
    paddingRight: 50,
    paddingTop: 15,
    paddingBottom: 15,
  },
  fillContainerAbsolute: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
}
