export default {
  centerBoth: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleText: {
    fontFamily: 'System',
    fontWeight: '100',
    color: 'rgba(255,255,255,1)',
    fontSize: 50,
  },
  locationText: {
    fontFamily: 'System',
    fontWeight: '100',
    color: 'rgba(255,255,255,1)',
    fontSize: 40,
  },
  buttonText: {
    fontFamily: 'System',
    fontWeight: 'normal',
    color: 'rgba(255,255,255,0.75)',
    fontSize: 30,
  },
  paragraphText: {
    fontFamily: 'HiraginoSans-W3',
    fontWeight: 'normal',
    color: 'rgba(255,255,255,0.75)',
    fontSize: 24,
    lineHeight: 28,
    textAlign: 'justify',
    width: 525,
  },
  button: {
    flexGrow: 0,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.75)',
    paddingLeft: 50,
    paddingRight: 50,
    paddingTop: 15,
    paddingBottom: 15,
  },
}
